/**
 * GitHub issue body template
 */

import { ParsedTask } from '../core/types.js';

/**
 * Generate issue body from task
 */
export function generateIssueBody(task: ParsedTask): string {
  const sections: string[] = [];

  // Description
  if (task.description) {
    sections.push(task.description);
    sections.push('');
  }

  // Metadata section
  const metadata: string[] = [];

  if (task.phase) {
    metadata.push(`**Phase:** ${task.phase}`);
  }

  if (task.metadata.milestone) {
    metadata.push(`**Milestone:** ${task.metadata.milestone}`);
  }

  if (task.metadata.target) {
    metadata.push(`**Target:** ${task.metadata.target}`);
  }

  if (task.metadata.dependencies && task.metadata.dependencies.length > 0) {
    metadata.push(`**Dependencies:** ${task.metadata.dependencies.join(', ')}`);
  }

  if (metadata.length > 0) {
    sections.push('## Details');
    sections.push(metadata.join('  \n'));
    sections.push('');
  }

  // Subtasks
  if (task.subTasks && task.subTasks.length > 0) {
    sections.push('## Subtasks');
    sections.push('');
    task.subTasks.forEach((subtask) => {
      sections.push(`- [ ] ${subtask}`);
    });
    sections.push('');
  }

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('_Generated by [claude-ticket-gen](https://github.com/offgriddev/claude-ticket-generator)_');

  return sections.join('\n');
}

/**
 * Generate title with optional prefix
 */
export function generateIssueTitle(task: ParsedTask): string {
  // Title is already in the task
  return task.title;
}

/**
 * Generate labels array from task
 */
export function generateLabels(task: ParsedTask): string[] {
  const labels: string[] = [...task.labels];

  // Add priority label
  labels.push(`priority-${getPriorityLabel(task.priority)}`);

  // Add type label
  labels.push(`type-${task.type}`);

  // Add optional label if applicable
  if (task.isOptional) {
    labels.push('optional');
  }

  return labels;
}

/**
 * Get priority label name
 */
function getPriorityLabel(priority: string): string {
  switch (priority) {
    case 'P0':
      return 'critical';
    case 'P1':
      return 'high';
    case 'P2':
      return 'medium';
    case 'P3':
      return 'low';
    default:
      return 'medium';
  }
}
